/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_pkg;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import model_pkg.Conexion;
/**
 *
 * @author Usuario
 */
public class frameCliclistas extends javax.swing.JFrame {
    Conexion con =new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel model;
    Object[] ciclista;

    /**
     * Creates new form frameCliclistas
     */
    public frameCliclistas() {
        initComponents();
        setLocationRelativeTo(this);
        show_ciclistas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        lb_identificacion = new javax.swing.JLabel();
        txt_identificacion = new javax.swing.JTextField();
        lb_contraseña = new javax.swing.JLabel();
        lb_confirmarContraseña = new javax.swing.JLabel();
        txt_Contraseña = new javax.swing.JTextField();
        txt_confirmarContraseña = new javax.swing.JTextField();
        btn_resgistrarse = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ciclistas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pagina Principal");

        lb_correo.setForeground(new java.awt.Color(255, 255, 255));
        lb_correo.setText("Correo");

        lb_identificacion.setForeground(new java.awt.Color(255, 255, 255));
        lb_identificacion.setText("Identificacion");

        lb_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        lb_contraseña.setText("Contraseña");

        lb_confirmarContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lb_confirmarContraseña.setText("Confirmar contraseña");

        txt_confirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmarContraseñaActionPerformed(evt);
            }
        });

        btn_resgistrarse.setForeground(new java.awt.Color(0, 0, 0));
        btn_resgistrarse.setText("Registrarse");
        btn_resgistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resgistrarseActionPerformed(evt);
            }
        });

        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("Iniciar sesion");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        tbl_ciclistas.setBackground(new java.awt.Color(0, 0, 204));
        tbl_ciclistas.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        tbl_ciclistas.setForeground(new java.awt.Color(0, 0, 0));
        tbl_ciclistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Correo", "Identificacion"
            }
        ));
        tbl_ciclistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ciclistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ciclistas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_resgistrarse)
                    .addComponent(lb_confirmarContraseña)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_identificacion)
                        .addComponent(lb_correo)
                        .addComponent(lb_contraseña)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_confirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_identificacion)
                    .addComponent(txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contraseña)
                    .addComponent(txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_confirmarContraseña)
                    .addComponent(txt_confirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_resgistrarse)
                    .addComponent(btn_login))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_confirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmarContraseñaActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        if(login()){
            dialog_rutas inst_dialog=new dialog_rutas(this, rootPaneCheckingEnabled);
            inst_dialog.setCiclista(ciclista);
            inst_dialog.show_ciclista();
            inst_dialog.setVisible(true);
        }else{
            JOptionPane.showConfirmDialog(this, "No se puede iniciar sesion");
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_resgistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resgistrarseActionPerformed
        // TODO add your handling code here:
        add_ciclista();
    }//GEN-LAST:event_btn_resgistrarseActionPerformed

    private void tbl_ciclistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ciclistasMouseClicked
        // TODO add your handling code here:
        int row= tbl_ciclistas.getSelectedRow();
        System.out.println(row);
        if(row>=0){
            String correo=tbl_ciclistas.getValueAt(row, 0).toString();
            String id=tbl_ciclistas.getValueAt(row, 1).toString();
         
            txt_correo.setText(correo);
            txt_identificacion.setText(id);
            
        }
    }//GEN-LAST:event_tbl_ciclistasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCliclistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCliclistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCliclistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCliclistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCliclistas().setVisible(true);
            }
        });
    }
    
    public void add_ciclista(){
        boolean igual;
        String correo = txt_correo.getText();
        String id = txt_identificacion.getText();
        String contrasena = txt_Contraseña.getText();
        String conContrasena = txt_confirmarContraseña.getText();
        if(contrasena.equalsIgnoreCase(conContrasena)){
            igual=true;
        }else{
            igual=false;
        }
        
        if(correo.isEmpty() || id.isEmpty() || contrasena.isEmpty() || conContrasena.isEmpty()){
            JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        } else {
            String query = "INSERT INTO tb_ciclistas(contrasena,correo,id)VALUES('"+contrasena+"','"+correo+"','"+id+"')";
            if(id_repetido(id)==false){
                if(igual==true){
                   try {
                      cn = con.getConnection();
                      st = cn.createStatement();
                      st.executeUpdate(query);
                      JOptionPane.showMessageDialog(this, "Se ha creado el registro con éxito");
                      clear_rows_table();
                      show_ciclistas();
                    } catch (SQLException e) {
                        System.out.println(e);
                         JOptionPane.showMessageDialog(this, "No se pudo crear el registro");
                        }
                }else{
                     JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
                }
            }else {
                JOptionPane.showMessageDialog(this, "No se puede registrar el ciclista");
            }
            
            
        }
    }
    
    public boolean login(){
        boolean iniciar=false;
        String contrasena = txt_Contraseña.getText();
        String conContrasena = txt_confirmarContraseña.getText();
        String correo = txt_correo.getText();
        String id = txt_identificacion.getText();
        boolean igual;
        if(contrasena.equalsIgnoreCase(conContrasena)){
            igual=true;
        }else{
            igual=false;
        }
        
        if(igual){
            String query="SELECT * FROM `tb_ciclistas`";
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                rs = st.executeQuery(query);          
                while(rs.next()){
                    if(rs.getString("correo").equals(correo) && rs.getString("contrasena").equals(contrasena)){
                        ciclista= new Object[2];
                        ciclista[0] = txt_correo.getText();
                        ciclista[1] = txt_identificacion.getText();
                        System.out.println(ciclista[0]);
                        
                        iniciar=true;
                    }
                }
            } catch (SQLException e) {
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "La contraseña y la confirmacion de la misma no coinciden");
        }
        
        
        
        return iniciar;
    }
    public void show_ciclistas(){
        String query = "SELECT * FROM tb_ciclistas";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(query);
            Object[] ciclista = new Object[2];
            model = (DefaultTableModel)tbl_ciclistas.getModel();
            while(rs.next()){
                ciclista[0] = rs.getString("correo");
                ciclista[1] = rs.getString("id");
                model.addRow(ciclista);
            }
            tbl_ciclistas.setModel(model);
        }catch(SQLException e){
            JOptionPane.showConfirmDialog(this, "No se encontraron registros de ciclistas");
        }
    }
    public boolean id_repetido(String nombre1){
        
        for (int i = 0; i < tbl_ciclistas.getRowCount(); i++) {
            if(nombre1.equalsIgnoreCase(tbl_ciclistas.getValueAt(i, 1).toString())){
                
                return true;
            }
        }
        return false;
    }
    
    public void clear_rows_table(){
        for (int i = 0; i < tbl_ciclistas.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
        txt_Contraseña.setText("");
        txt_confirmarContraseña.setText("");
        txt_correo.setText("");
        txt_identificacion.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_resgistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_confirmarContraseña;
    private javax.swing.JLabel lb_contraseña;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_identificacion;
    private javax.swing.JTable tbl_ciclistas;
    private javax.swing.JTextField txt_Contraseña;
    private javax.swing.JTextField txt_confirmarContraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_identificacion;
    // End of variables declaration//GEN-END:variables
}
